name: background_patterns
description: Package that enables you to implement glorious backgrounds with customizable patterns and shapes
version: 0.0.6
homepage: https://github.com/WilkoThomassen/flutter_background_patterns

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
